#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_BLL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="blockchain")]
	public partial class QL_KHOAHOCDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertcourse(course instance);
    partial void Updatecourse(course instance);
    partial void Deletecourse(course instance);
    partial void InsertCourseRegistrationHistory(CourseRegistrationHistory instance);
    partial void UpdateCourseRegistrationHistory(CourseRegistrationHistory instance);
    partial void DeleteCourseRegistrationHistory(CourseRegistrationHistory instance);
    partial void InsertClassDetail(ClassDetail instance);
    partial void UpdateClassDetail(ClassDetail instance);
    partial void DeleteClassDetail(ClassDetail instance);
    partial void InsertTokenWithdrawal(TokenWithdrawal instance);
    partial void UpdateTokenWithdrawal(TokenWithdrawal instance);
    partial void DeleteTokenWithdrawal(TokenWithdrawal instance);
    partial void InsertUserRole(UserRole instance);
    partial void UpdateUserRole(UserRole instance);
    partial void DeleteUserRole(UserRole instance);
    #endregion
		
		public QL_KHOAHOCDataContext() : 
				base(global::DAL_BLL.Properties.Settings.Default.blockchainConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QL_KHOAHOCDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QL_KHOAHOCDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QL_KHOAHOCDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QL_KHOAHOCDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<UserAttendance> UserAttendances
		{
			get
			{
				return this.GetTable<UserAttendance>();
			}
		}
		
		public System.Data.Linq.Table<course> courses
		{
			get
			{
				return this.GetTable<course>();
			}
		}
		
		public System.Data.Linq.Table<CourseRegistrationHistory> CourseRegistrationHistories
		{
			get
			{
				return this.GetTable<CourseRegistrationHistory>();
			}
		}
		
		public System.Data.Linq.Table<info> infos
		{
			get
			{
				return this.GetTable<info>();
			}
		}
		
		public System.Data.Linq.Table<notification> notifications
		{
			get
			{
				return this.GetTable<notification>();
			}
		}
		
		public System.Data.Linq.Table<ClassDetail> ClassDetails
		{
			get
			{
				return this.GetTable<ClassDetail>();
			}
		}
		
		public System.Data.Linq.Table<TokenWithdrawal> TokenWithdrawals
		{
			get
			{
				return this.GetTable<TokenWithdrawal>();
			}
		}
		
		public System.Data.Linq.Table<UserRole> UserRoles
		{
			get
			{
				return this.GetTable<UserRole>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UserAttendance")]
	public partial class UserAttendance
	{
		
		private System.Nullable<int> _courseId;
		
		private string _address;
		
		private System.Nullable<int> _sessionNumber;
		
		private System.Nullable<byte> _attended;
		
		public UserAttendance()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_courseId", DbType="Int")]
		public System.Nullable<int> courseId
		{
			get
			{
				return this._courseId;
			}
			set
			{
				if ((this._courseId != value))
				{
					this._courseId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="VarChar(100)")]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this._address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sessionNumber", DbType="Int")]
		public System.Nullable<int> sessionNumber
		{
			get
			{
				return this._sessionNumber;
			}
			set
			{
				if ((this._sessionNumber != value))
				{
					this._sessionNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_attended", DbType="TinyInt")]
		public System.Nullable<byte> attended
		{
			get
			{
				return this._attended;
			}
			set
			{
				if ((this._attended != value))
				{
					this._attended = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.course")]
	public partial class course : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<double> _price;
		
		private System.Nullable<int> _session;
		
		private string _status;
		
		private string _image;
		
		private EntitySet<CourseRegistrationHistory> _CourseRegistrationHistories;
		
		private EntitySet<ClassDetail> _ClassDetails;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnpriceChanging(System.Nullable<double> value);
    partial void OnpriceChanged();
    partial void OnsessionChanging(System.Nullable<int> value);
    partial void OnsessionChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    partial void OnimageChanging(string value);
    partial void OnimageChanged();
    #endregion
		
		public course()
		{
			this._CourseRegistrationHistories = new EntitySet<CourseRegistrationHistory>(new Action<CourseRegistrationHistory>(this.attach_CourseRegistrationHistories), new Action<CourseRegistrationHistory>(this.detach_CourseRegistrationHistories));
			this._ClassDetails = new EntitySet<ClassDetail>(new Action<ClassDetail>(this.attach_ClassDetails), new Action<ClassDetail>(this.detach_ClassDetails));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Float")]
		public System.Nullable<double> price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this.OnpriceChanging(value);
					this.SendPropertyChanging();
					this._price = value;
					this.SendPropertyChanged("price");
					this.OnpriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_session", DbType="Int")]
		public System.Nullable<int> session
		{
			get
			{
				return this._session;
			}
			set
			{
				if ((this._session != value))
				{
					this.OnsessionChanging(value);
					this.SendPropertyChanging();
					this._session = value;
					this.SendPropertyChanged("session");
					this.OnsessionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="NVarChar(50)")]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image", DbType="NVarChar(MAX)")]
		public string image
		{
			get
			{
				return this._image;
			}
			set
			{
				if ((this._image != value))
				{
					this.OnimageChanging(value);
					this.SendPropertyChanging();
					this._image = value;
					this.SendPropertyChanged("image");
					this.OnimageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="course_CourseRegistrationHistory", Storage="_CourseRegistrationHistories", ThisKey="id", OtherKey="courseId")]
		public EntitySet<CourseRegistrationHistory> CourseRegistrationHistories
		{
			get
			{
				return this._CourseRegistrationHistories;
			}
			set
			{
				this._CourseRegistrationHistories.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="course_ClassDetail", Storage="_ClassDetails", ThisKey="id", OtherKey="courseId")]
		public EntitySet<ClassDetail> ClassDetails
		{
			get
			{
				return this._ClassDetails;
			}
			set
			{
				this._ClassDetails.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CourseRegistrationHistories(CourseRegistrationHistory entity)
		{
			this.SendPropertyChanging();
			entity.course = this;
		}
		
		private void detach_CourseRegistrationHistories(CourseRegistrationHistory entity)
		{
			this.SendPropertyChanging();
			entity.course = null;
		}
		
		private void attach_ClassDetails(ClassDetail entity)
		{
			this.SendPropertyChanging();
			entity.course = this;
		}
		
		private void detach_ClassDetails(ClassDetail entity)
		{
			this.SendPropertyChanging();
			entity.course = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CourseRegistrationHistory")]
	public partial class CourseRegistrationHistory : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _registrationId;
		
		private int _courseId;
		
		private string _senderAddress;
		
		private System.Nullable<System.DateTime> _registrationTime;
		
		private string _transactionHash;
		
		private EntityRef<course> _course;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnregistrationIdChanging(int value);
    partial void OnregistrationIdChanged();
    partial void OncourseIdChanging(int value);
    partial void OncourseIdChanged();
    partial void OnsenderAddressChanging(string value);
    partial void OnsenderAddressChanged();
    partial void OnregistrationTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnregistrationTimeChanged();
    partial void OntransactionHashChanging(string value);
    partial void OntransactionHashChanged();
    #endregion
		
		public CourseRegistrationHistory()
		{
			this._course = default(EntityRef<course>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_registrationId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int registrationId
		{
			get
			{
				return this._registrationId;
			}
			set
			{
				if ((this._registrationId != value))
				{
					this.OnregistrationIdChanging(value);
					this.SendPropertyChanging();
					this._registrationId = value;
					this.SendPropertyChanged("registrationId");
					this.OnregistrationIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_courseId", DbType="Int NOT NULL")]
		public int courseId
		{
			get
			{
				return this._courseId;
			}
			set
			{
				if ((this._courseId != value))
				{
					if (this._course.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncourseIdChanging(value);
					this.SendPropertyChanging();
					this._courseId = value;
					this.SendPropertyChanged("courseId");
					this.OncourseIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_senderAddress", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string senderAddress
		{
			get
			{
				return this._senderAddress;
			}
			set
			{
				if ((this._senderAddress != value))
				{
					this.OnsenderAddressChanging(value);
					this.SendPropertyChanging();
					this._senderAddress = value;
					this.SendPropertyChanged("senderAddress");
					this.OnsenderAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_registrationTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> registrationTime
		{
			get
			{
				return this._registrationTime;
			}
			set
			{
				if ((this._registrationTime != value))
				{
					this.OnregistrationTimeChanging(value);
					this.SendPropertyChanging();
					this._registrationTime = value;
					this.SendPropertyChanged("registrationTime");
					this.OnregistrationTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_transactionHash", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string transactionHash
		{
			get
			{
				return this._transactionHash;
			}
			set
			{
				if ((this._transactionHash != value))
				{
					this.OntransactionHashChanging(value);
					this.SendPropertyChanging();
					this._transactionHash = value;
					this.SendPropertyChanged("transactionHash");
					this.OntransactionHashChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="course_CourseRegistrationHistory", Storage="_course", ThisKey="courseId", OtherKey="id", IsForeignKey=true)]
		public course course
		{
			get
			{
				return this._course.Entity;
			}
			set
			{
				course previousValue = this._course.Entity;
				if (((previousValue != value) 
							|| (this._course.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._course.Entity = null;
						previousValue.CourseRegistrationHistories.Remove(this);
					}
					this._course.Entity = value;
					if ((value != null))
					{
						value.CourseRegistrationHistories.Add(this);
						this._courseId = value.id;
					}
					else
					{
						this._courseId = default(int);
					}
					this.SendPropertyChanged("course");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.info")]
	public partial class info
	{
		
		private System.Nullable<int> _id;
		
		private string _gmail;
		
		private string _address;
		
		public info()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int")]
		public System.Nullable<int> id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gmail", DbType="VarChar(50)")]
		public string gmail
		{
			get
			{
				return this._gmail;
			}
			set
			{
				if ((this._gmail != value))
				{
					this._gmail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="VarChar(100)")]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this._address = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.notifications")]
	public partial class notification
	{
		
		private System.Nullable<int> _id;
		
		private string _notification1;
		
		private string _zoom_link;
		
		private System.Nullable<int> _session_number;
		
		private System.Nullable<System.DateTime> _created_at;
		
		public notification()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int")]
		public System.Nullable<int> id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="notification", Storage="_notification1", DbType="VarChar(255)")]
		public string notification1
		{
			get
			{
				return this._notification1;
			}
			set
			{
				if ((this._notification1 != value))
				{
					this._notification1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zoom_link", DbType="VarChar(255)")]
		public string zoom_link
		{
			get
			{
				return this._zoom_link;
			}
			set
			{
				if ((this._zoom_link != value))
				{
					this._zoom_link = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_session_number", DbType="Int")]
		public System.Nullable<int> session_number
		{
			get
			{
				return this._session_number;
			}
			set
			{
				if ((this._session_number != value))
				{
					this._session_number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_at", DbType="DateTime")]
		public System.Nullable<System.DateTime> created_at
		{
			get
			{
				return this._created_at;
			}
			set
			{
				if ((this._created_at != value))
				{
					this._created_at = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ClassDetails")]
	public partial class ClassDetail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _classId;
		
		private int _courseId;
		
		private string _className;
		
		private string _classDescription;
		
		private System.DateTime _startTime;
		
		private System.DateTime _endTime;
		
		private EntityRef<course> _course;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnclassIdChanging(int value);
    partial void OnclassIdChanged();
    partial void OncourseIdChanging(int value);
    partial void OncourseIdChanged();
    partial void OnclassNameChanging(string value);
    partial void OnclassNameChanged();
    partial void OnclassDescriptionChanging(string value);
    partial void OnclassDescriptionChanged();
    partial void OnstartTimeChanging(System.DateTime value);
    partial void OnstartTimeChanged();
    partial void OnendTimeChanging(System.DateTime value);
    partial void OnendTimeChanged();
    #endregion
		
		public ClassDetail()
		{
			this._course = default(EntityRef<course>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_classId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int classId
		{
			get
			{
				return this._classId;
			}
			set
			{
				if ((this._classId != value))
				{
					this.OnclassIdChanging(value);
					this.SendPropertyChanging();
					this._classId = value;
					this.SendPropertyChanged("classId");
					this.OnclassIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_courseId", DbType="Int NOT NULL")]
		public int courseId
		{
			get
			{
				return this._courseId;
			}
			set
			{
				if ((this._courseId != value))
				{
					if (this._course.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncourseIdChanging(value);
					this.SendPropertyChanging();
					this._courseId = value;
					this.SendPropertyChanged("courseId");
					this.OncourseIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_className", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string className
		{
			get
			{
				return this._className;
			}
			set
			{
				if ((this._className != value))
				{
					this.OnclassNameChanging(value);
					this.SendPropertyChanging();
					this._className = value;
					this.SendPropertyChanged("className");
					this.OnclassNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_classDescription", DbType="NVarChar(MAX)")]
		public string classDescription
		{
			get
			{
				return this._classDescription;
			}
			set
			{
				if ((this._classDescription != value))
				{
					this.OnclassDescriptionChanging(value);
					this.SendPropertyChanging();
					this._classDescription = value;
					this.SendPropertyChanged("classDescription");
					this.OnclassDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_startTime", DbType="DateTime NOT NULL")]
		public System.DateTime startTime
		{
			get
			{
				return this._startTime;
			}
			set
			{
				if ((this._startTime != value))
				{
					this.OnstartTimeChanging(value);
					this.SendPropertyChanging();
					this._startTime = value;
					this.SendPropertyChanged("startTime");
					this.OnstartTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_endTime", DbType="DateTime NOT NULL")]
		public System.DateTime endTime
		{
			get
			{
				return this._endTime;
			}
			set
			{
				if ((this._endTime != value))
				{
					this.OnendTimeChanging(value);
					this.SendPropertyChanging();
					this._endTime = value;
					this.SendPropertyChanged("endTime");
					this.OnendTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="course_ClassDetail", Storage="_course", ThisKey="courseId", OtherKey="id", IsForeignKey=true)]
		public course course
		{
			get
			{
				return this._course.Entity;
			}
			set
			{
				course previousValue = this._course.Entity;
				if (((previousValue != value) 
							|| (this._course.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._course.Entity = null;
						previousValue.ClassDetails.Remove(this);
					}
					this._course.Entity = value;
					if ((value != null))
					{
						value.ClassDetails.Add(this);
						this._courseId = value.id;
					}
					else
					{
						this._courseId = default(int);
					}
					this.SendPropertyChanged("course");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TokenWithdrawals")]
	public partial class TokenWithdrawal : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _sender_address;
		
		private string _recipient_address;
		
		private decimal _amount;
		
		private string _transaction_hash;
		
		private string _status;
		
		private System.Nullable<System.DateTime> _created_at;
		
		private System.Nullable<System.DateTime> _updated_at;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onsender_addressChanging(string value);
    partial void Onsender_addressChanged();
    partial void Onrecipient_addressChanging(string value);
    partial void Onrecipient_addressChanged();
    partial void OnamountChanging(decimal value);
    partial void OnamountChanged();
    partial void Ontransaction_hashChanging(string value);
    partial void Ontransaction_hashChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    partial void Oncreated_atChanging(System.Nullable<System.DateTime> value);
    partial void Oncreated_atChanged();
    partial void Onupdated_atChanging(System.Nullable<System.DateTime> value);
    partial void Onupdated_atChanged();
    #endregion
		
		public TokenWithdrawal()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sender_address", DbType="VarChar(42) NOT NULL", CanBeNull=false)]
		public string sender_address
		{
			get
			{
				return this._sender_address;
			}
			set
			{
				if ((this._sender_address != value))
				{
					this.Onsender_addressChanging(value);
					this.SendPropertyChanging();
					this._sender_address = value;
					this.SendPropertyChanged("sender_address");
					this.Onsender_addressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_recipient_address", DbType="VarChar(42) NOT NULL", CanBeNull=false)]
		public string recipient_address
		{
			get
			{
				return this._recipient_address;
			}
			set
			{
				if ((this._recipient_address != value))
				{
					this.Onrecipient_addressChanging(value);
					this.SendPropertyChanging();
					this._recipient_address = value;
					this.SendPropertyChanged("recipient_address");
					this.Onrecipient_addressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_amount", DbType="Decimal(38,18) NOT NULL")]
		public decimal amount
		{
			get
			{
				return this._amount;
			}
			set
			{
				if ((this._amount != value))
				{
					this.OnamountChanging(value);
					this.SendPropertyChanging();
					this._amount = value;
					this.SendPropertyChanged("amount");
					this.OnamountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_transaction_hash", DbType="VarChar(66)")]
		public string transaction_hash
		{
			get
			{
				return this._transaction_hash;
			}
			set
			{
				if ((this._transaction_hash != value))
				{
					this.Ontransaction_hashChanging(value);
					this.SendPropertyChanging();
					this._transaction_hash = value;
					this.SendPropertyChanged("transaction_hash");
					this.Ontransaction_hashChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="VarChar(10)")]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_at", DbType="DateTime")]
		public System.Nullable<System.DateTime> created_at
		{
			get
			{
				return this._created_at;
			}
			set
			{
				if ((this._created_at != value))
				{
					this.Oncreated_atChanging(value);
					this.SendPropertyChanging();
					this._created_at = value;
					this.SendPropertyChanged("created_at");
					this.Oncreated_atChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updated_at", DbType="DateTime")]
		public System.Nullable<System.DateTime> updated_at
		{
			get
			{
				return this._updated_at;
			}
			set
			{
				if ((this._updated_at != value))
				{
					this.Onupdated_atChanging(value);
					this.SendPropertyChanging();
					this._updated_at = value;
					this.SendPropertyChanged("updated_at");
					this.Onupdated_atChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UserRoles")]
	public partial class UserRole : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _address;
		
		private string _role;
		
		private byte _status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    partial void OnroleChanging(string value);
    partial void OnroleChanged();
    partial void OnstatusChanging(byte value);
    partial void OnstatusChanged();
    #endregion
		
		public UserRole()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="VarChar(42) NOT NULL", CanBeNull=false)]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this.OnaddressChanging(value);
					this.SendPropertyChanging();
					this._address = value;
					this.SendPropertyChanged("address");
					this.OnaddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_role", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string role
		{
			get
			{
				return this._role;
			}
			set
			{
				if ((this._role != value))
				{
					this.OnroleChanging(value);
					this.SendPropertyChanging();
					this._role = value;
					this.SendPropertyChanged("role");
					this.OnroleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="TinyInt NOT NULL")]
		public byte status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
